config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'signup' => 'users#new'

  root 'static_pages#home'

  get 'help' =>  'static_pages#help'
  get 'about' =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'

  get 'new_bar' => 'bars#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :bars 
  resources :deals,     only: [:create, :destroy] 

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  has_many :deals, dependent: :destroy
  before_save {self.address = address.downcase}
  validates :name, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: true}
  validates :address, presence: true, length: {maximum: 255}
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :bar
  validates :bar_id, presence: true
  validates :content, presence: true, length: {maximum: 140}

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save {self.email = email.downcase }

  validates :name, presence: true, length: {maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true

  has_secure_password

  validates :password, presence: true, length: {minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render text: "hello, world! From Landon"
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController  

  def destroy
    Bar.find(params[:id]).destroy
    flash[:success] = "Bar Deleted"
    redirect_to bars_url
  end

  def index
    @bars = Bar.paginate(page: params[:page])
  end

  def show
    @bar = Bar.find(params[:id])
    @deals = @bar.deals
    @deal = @bar.deals.build
  end

  def new
    @bar = Bar.new
    @deal = @bar.deals.build
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
      flash[:success] = "Succesfully added Bar!"
      redirect_to @bar
    else
      render 'new'
    end
  end

  def edit
    @bar = Bar.find(params[:id])
  end


  def update
    @bar = Bar.find(params[:id])
    if @bar.update_attributes(bar_params)
      flash[:success] = "Bar updated"
      redirect_to @bar
    else
      render 'edit'
    end
  end


  private
  def bar_params
    params.require(:bar).permit(:name, :address)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def create
    @bar = Bar.find(bar_params[:bar_id])
    @deal = @bar.deals.build(bar_params)
    if @deal.save
      flash[:success] = "Deal Created"
      redirect_to @bar
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end
  
  private

  def bar_params
    params.require(:deal).permit(:content, :day, :bar_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)  
    if @user.save
      flash[:success] = "Sign up Successful"
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end  
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bars/_bar.html.erb
<li>
<%= link_to bar.name, bar %>
 | <%= link_to "Edit", edit_bar_path(bar) %>
 | <%= link_to "Delete", bar, method: :delete,data: { confirm: "You sure?" } %> 
</li>

app/views/bars/edit.html.erb
<% provide(:title, "Edit Bar") %>
<h1>Update Bar</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@bar) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/bars/index.html.erb
<% provide(:title, 'All Bars') %>
<h1>All Bars</h1>
<div class="text-right">
  <%= link_to "Add Bar", new_bar_path, class: "btn btn-sm btn-primary" %>
</div>
<%= will_paginate %>
<ul class="bars">
  <% @bars.each do |bar| %>
    <%= render bar %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/bars/new.html.erb
<% provide(:title, 'Add Bar') %>
<h1>Add Bar</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@bar) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.submit "Add Bar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bars/show.html.erb
<% provide(:title, @bar.name) %>
<%= flash[:message]%>

<h1><%= @bar.name %></h1>
<p><%= @bar.address %></p>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Deals</h3>
      <% if @bar.deals.any? %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Day</th>
              <th>Deal</th>
            </tr>
          </thead>
          <tbody>
            <% @bar.deals.each do |deal| %>
              <%= render deal %>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="col-md-6">
      <h3>Add Deal</h3>
      <%= render 'shared/deal_form' %>
    </div>
  </div>
</div>

app/views/deals/_deal.html.erb
<tr>
  <td>
    <%= deal.day %>
  </td>
  <td>
    <%= deal.content %>
  </td>
</tr>

app/views/deals/_deal_form.html.erb
<%= form_for(@deals) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :day, placeholder: "Compose new deal..." %>
    <%= f.text_area :content, placeholder: "Compose new deal..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Landon Grim is making this.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Landon's Bars", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Bars", bars_path %> </li>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Landon's Bars</title>
    <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
    </head>
    <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%=message_type%>"><%= message %> </div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </body>
  </html>

app/views/shared/_deal_form.html.erb
<%= form_for(@deal) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.hidden_field :bar_id , :value=>@bar.id %>
    </br>
    <%= f.label :day%>
    <%= f.text_area :day%>
    <%= f.label :info%>
    <%= f.text_area :content%>
  </div>

  <%= f.submit "Add Deal", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @bar.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@bar.errors.count, "error") %>.
    </div>
    <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_signup_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is Landon Grim's web application which lists some bars he and his friends go to.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Landon Grim at grim.70@osu.edu
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  If you need help email grim.70@osu.edu
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Grim's Bars</h1>
  <h2>
    Welcome to Landon Grim's website of Columbus Bars
  </h2>
  <%= link_to "Bars", bars_path, class: "btn btn-lg btn-primary" %>
</div

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/signup_errors' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %></h1>
<p><%= @user.email %></p>